pipeline {
    agent any

    environment {
        // Docker Hub credentials ID stored in Jenkins credentials store
        DOCKER_CREDENTIALS_ID = 'dockerhub-credentials' //stored on jenkins
        // Docker Hub username and repository name
        DOCKER_USERNAME = 'your-dockerhub-username' // user123
        DOCKER_REPO = 'log_file_analysis' // log_file_analysis
        // Full Docker image name
        IMAGE_NAME = "${DOCKER_USERNAME}/${DOCKER_REPO}"
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from Github Version control
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image
                    sh "docker build -t ${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    // Login to Docker Hub
                    withDockerRegistry([credentialsId: "${DOCKER_CREDENTIALS_ID}", url: '']) {
                        // Push Docker image with "latest" tag
                        sh "docker push ${IMAGE_NAME}:latest"
                    }
                }
            }
        }
    }

    post {
        always {
            // Clean up Docker image to save space
            sh "docker rmi ${IMAGE_NAME}:latest || true"
        }
    }
}
